version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - .:/pyStock
    - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn pyStock.wsgi:application --bind 0.0.0.0:8000
    volumes:
    - .:/pyStock/
    expose:
      - "8000"
